name: mextv_app
description: MexTV


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  http: ^0.12.0+1
  cached_network_image: ^0.7.0
  flutter_platform_widgets: ^0.9.5
  carousel_pro: ^0.0.13
  audioplayer: ^0.5.2
  flutter_webview_plugin:
  path_provider: ^0.5.0+1
  sqflite: any
  share:
  youtube_player: ^3.4.1
  media_player: ^0.0.6
  flutter_radio:
  # youtube_player_flutter: ^1.1.1+1
#  audioplayers: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/image_11.jpg
    - assets/images/radiobanner.jpg
    - assets/images/video.jpg
    - assets/images/image_30.jpg
    - assets/images/photo_singer_female.jpg
    - assets/images/mex_tv_logo_small.png
    - assets/images/mex_radio_logo_small.png
    - assets/images/cnews.jpeg
    - assets/images/livetv.jpeg
    - assets/images/mexevent.jpeg
    - assets/images/banner1.jpg
    - assets/images/banner2.jpg
    - assets/images/banner3.jpg
    - assets/images/banner4.jpg
    - assets/images/banner5.jpg
    - assets/images/banner6.jpg


  fonts:
     - family: Ebrima
       fonts:
         - asset: assets/fonts/ebrima.ttf
         - asset: assets/fonts/ebrimabd.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
